name: ARM64 Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写 docker 镜像名称，多个用英文逗号分开'
        required: true
        default: 'alpine:latest,ubuntu:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Save Docker Images
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/arm64"
          docker save "${image}" -o "${image//\//_}-arm64.tar"
        done

    - name: Compress the TAR files
      run: |
       for file in *.tar; do
           tar -czf "${file%.tar}.tar.gz" "$file"
       done
