name: Sync Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,debian:latest,debian:11,ubuntu:latest,ubuntu:22.04,ubuntu:20.04'

jobs:
  sync-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Images
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/arm64"
          docker save "${image}" -o "${image//\//_}-arm64.tar"
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "${image//\//_}-amd64.tar"
        done
        
    - name: Compress the TAR files
      run: |
        chmod +x compress_tar.sh
        ./compress_tar.sh
        
    - name: set key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GIT_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        
    - name: Push Web server
      env:
        SECRET_CHECK_SCRIPT_URL: ${{ secrets.SECRET_CHECK_SCRIPT_URL }}
      run: rsync -avz ./*.tar.gz "$SECRET_CHECK_SCRIPT_URL"
      
    - name: upload artifact amd64
      uses: actions/upload-artifact@v4
      with:
          name: Docker-amd64-images
          path: ./*amd64.tar.gz
          
    - name: upload artifact arm64 
      uses: actions/upload-artifact@v4
      with:
          name: Docker-arm64-images
          path: ./*arm64.tar.gz 
          
    - name: Clean up intermediate files
      run: |
        rm *-arm64.tar
        rm *-amd64.tar
